### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by CodingGlad** [CodingGlad/HackathonCZM#2]

**Comment by CodingGlad** [comment]
Bude ukládat rezervaci uživatele - jméno, přijmení, email, telefon, jestli má uskladněné pneu pro uživatele.
Budeme ukládt info o autě - spz
Budeme ukládat info o uskladněném pneu - stáří, jak moc je sjetý vzorek, začka pneu, velikost pneu, místo ve skladu.
Musíme ukládat i historii zákazníka.

**Comment by Efimover** [comment]
created tables:

CREATE TABLE Drivers (
    id_driver int primary key,
    telephone varchar(15) unique,
    name varchar(50) not null,
    surname varchar(50) not null,
    email varchar(50) not null
);

CREATE TABLE Cars (
    spz varchar(15) primary key,
    type varchar not null,
    facture varchar not null
);

CREATE TABLE Reservation(
    number_of_reservation int primary key,
    telephone_driver varchar(15),
    spz_car varchar(50),
    FOREIGN KEY (telephone_driver) REFERENCES Drivers(telephone),
    FOREIGN KEY (spz_car) REFERENCES Cars(spz)
);

CREATE TABLE  Types (
    code int primary key,
    spz_of_car_pneu int,
    FOREIGN KEY (spz_of_car_pneu) REFERENCES Cars(spz),
    treads int,
    size int,
    price varchar(15),
    season_type varchar(15),
    isStored boolean
);

**Comment by CodingGlad** [comment]
CREATE TABLE Drivers (
	telephone varchar(9) primary key,
	name varchar(25) not null,
	surname varchar(25) not null,
	email varchar(75) not null
);

CREATE TABLE Cars (
	spz varchar(7) primary key,
	manufacturer varchar(30) not null,
	model varchar(30) not null
);

CREATE TABLE Reservation (
	number_of_reservation varchar(36) primary key,
	date_of_reservtion timestamp not null,
	telephone_driver varchar(9) not null,
	spz_of_car varchar(7) not null,
	FOREIGN KEY (telephone_driver) REFERENCES Drivers(telephone),
	FOREIGN KEY (spz_of_car) REFERENCES Cars(spz)
);

CREATE TABLE Tires (
	code varchar(36) primary key,
	spz_of_car varchar(7) not null,
	depth_of_treads int,
	size_of_tires varchar(6),
	tire_manufacturer varchar(20),
	is_stored boolean not null,
	place_in_storage varchar(15),
	season_type varchar(15) not null,
	FOREIGN KEY (spz_of_car) REFERENCES Cars(spz)
);

**Comment by CodingGlad** [comment]
CREATE TABLE Drivers (
	telephone varchar(9) primary key,
	name varchar(25) not null,
	surname varchar(25) not null,
	email varchar(75) not null
);

CREATE TABLE Cars (
	spz varchar(7) primary key,
	manufacturer varchar(30) not null,
	model varchar(30) not null
);

CREATE TABLE Reservation (
	number_of_reservation varchar(36) primary key,
	date_of_reservtion timestamp not null,
	telephone_driver varchar(9) not null,
	spz_of_car varchar(7) not null,
	type_of_work varchar(10) not null,
	notes text,
	FOREIGN KEY (telephone_driver) REFERENCES Drivers(telephone),
	FOREIGN KEY (spz_of_car) REFERENCES Cars(spz)
);

CREATE TABLE Tires (
	code varchar(36) primary key,
	spz_of_car varchar(7) not null,
	depth_of_treads int,
	size_of_tires varchar(6),
	tire_manufacturer varchar(20),
	is_stored boolean not null,
	place_in_storage varchar(15),
	season_type varchar(15) not null,
	notes text,
	FOREIGN KEY (spz_of_car) REFERENCES Cars(spz)
);

**Comment by CodingGlad** [comment]
CREATE TABLE Drivers (
	telephone varchar(9) primary key,
	name varchar(25) not null,
	surname varchar(25) not null,
	email varchar(75) not null
);

CREATE TABLE Cars (
	spz varchar(7) primary key,
	manufacturer varchar(30) not null,
	model varchar(30) not null
);

CREATE TABLE Reservation (
	number_of_reservation varchar(36) primary key,
	date_of_reservation timestamp not null,
	telephone_driver varchar(9) not null,
	spz_of_car varchar(7) not null,
	type_of_work varchar(10) not null,
	notes text,
	FOREIGN KEY (telephone_driver) REFERENCES Drivers(telephone),
	FOREIGN KEY (spz_of_car) REFERENCES Cars(spz)
);

CREATE TABLE Tires (
	code varchar(36) primary key,
	spz_of_car varchar(7) not null,
	depth_of_treads int,
	size_of_tires varchar(6),
	tire_manufacturer varchar(20),
	is_stored varchar(10) not null,
	place_in_storage varchar(15),
	season_type varchar(15) not null,
	notes text,
	FOREIGN KEY (spz_of_car) REFERENCES Cars(spz)
);

**Comment by CodingGlad** [comment]
CREATE TABLE Drivers (
	telephone text primary key,
	name text not null,
	surname text not null,
	email text not null
);

CREATE TABLE Cars (
	spz text primary key,
	manufacturer text not null,
	model text not null
);

CREATE TABLE Reservation (
	number_of_reservation text primary key,
	date_of_reservation timestamp not null,
	telephone_driver text not null,
	spz_of_car text not null,
	type_of_work text,
	notes text,
	FOREIGN KEY (telephone_driver) REFERENCES Drivers(telephone),
	FOREIGN KEY (spz_of_car) REFERENCES Cars(spz)
);

CREATE TABLE Tires (
	code text primary key,
	spz_of_car text not null,
	depth_of_treads int,
	size_of_tires text,
	tire_manufacturer text,
	is_stored text not null,
	place_in_storage text,
	season_type text not null,
	notes text,
	FOREIGN KEY (spz_of_car) REFERENCES Cars(spz)
);
